import "./globals.css";
import { Inter } from "next/font/google";

import Header from "./components/Header";
import Footer from "./components/Footer";
import Head from "next/head";
import DashBoard from "./components/DashBoard";
import Pagination from "./components/Pagination";
import Providers from "./Providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "News Page",
  description: "News Page",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <title>News App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <body>
        <Header />
        <div className="flex mt-13 ">
          <DashBoard />

          <main className="bg-slate-900 mt-0">
            <Providers>{children}</Providers>
          </main>
        </div>
        <Pagination />

        <Footer />
      </body>
    </html>
  );
}
